"""full_schema

Revision ID: 4e588ae574ed
Revises: 
Create Date: 2026-05-06 17:13:53.329771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e588ae574ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'workout_hours_per_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('workout_hours_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
