"""add_subscription_fields

Revision ID: f909000e2b92
Revises: 4e588ae574ed
Create Date: 2026-05-18 11:13:28.002859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f909000e2b92'
down_revision: Union[str, None] = '4e588ae574ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'workout_hours_per_week')
    op.add_column('users', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('subscription_type', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('subscription_active', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_active')
    op.drop_column('users', 'subscription_type')
    op.drop_column('users', 'email')
    op.add_column('profiles', sa.Column('workout_hours_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
